### ISSUE TITLE
postcss-import chokes on modular scale declarations

### ISSUE THREAD

**Issue by adrinux** [kristoferjoseph/postcss-modular-scale#11]
Declaring scale like so:

```
:root {
  --ms-bases = 1;
  --ms-ratios = 1.067;
}
```

In a separate typography.css which I'm @importing into main.css causes an error:

```
typography.css:2:3: Unknown word [postcss-import]
```

Regardless of whether postcss-modular-scale is run before postcss-import or after.

Any suggestions for workarounds?

**Comment by kristoferjoseph** [comment]
Do me a favor, try it with two bases set and see if the error goes away. Thanks!
I am going to be removing support for multiple bases and ratios soon.

**Comment by adrinux** [comment]
Sorry I switched to https://github.com/erikjung/postcss-modular-scale-unit – don't even have your module installed to test.

**Comment by lkraav** [comment]
hey @adrinux. as @kristoferjoseph is busy with other things, can you comment on how well https://github.com/erikjung/postcss-modular-scale-unit as worked out for you? i think will also need to go with an alternative, as this one simply doesn't work.
