### ISSUE TITLE
`:root` - add introductory documentation?

### ISSUE THREAD

**Issue by lkraav** [kristoferjoseph/postcss-modular-scale#23]
https://github.com/MadLittleMods/postcss-css-variables#defining-custom-properties-with--- has `:root` nicely spelled out. Because happy follow-up search results can't be guaranteed, perhaps useful to add similar information here.

Also, is there ever a reason to define `m-s` at a restricted scope, lower than `:root`? If not, is it possible to initialize `m-s` without specifying `:root` in the first place?

**Comment by kristoferjoseph** [comment]
Using :root is the onky guaranteed way for this plugin to work. It is documented as such.
