### ISSUE TITLE
How to use it? 

### ISSUE THREAD

**Issue by kodekrendel** [kristoferjoseph/postcss-modular-scale#26]
Hi. May be I am stupid, but this plugin doesn't make no sense to me.

I use modularscale.com to generate scales before. 
Trying this plugin, and can't understand how to use it.
For example.

```
:root {
  --ms-bases: 1, 0.75;
  --ms-ratios: 2;
}

h1 {
  font-size: ms(4)rem;
}
```
Outputs me `font-size: 6.854rem;` If I set `ms(1)rem` then `1.618rem`

1. Why is that number? 
2. How to set my own scale, for example perfect fifth?
4. Why to values --ms-bases? What is this? Example explains nothing to me
5. Changing --ms-ratios do nothing

**Comment by kodekrendel** [comment]
Changing this values makes no effect, it still make golden ratio.

```
:root {
  --ms-bases: 11, 111.75;
  --ms-ratios: 29;
}
```

**Comment by mrmartineau** [comment]
@kodekrendel this issue has been raised in #24.

**Comment by kodekrendel** [comment]
Thanks for clarifying. Otherwise I thought the problem is me (second day with PostCSS). Happily, that's not the only one Modular Scale plugin.
