### ISSUE TITLE
The ms() no semantics

### ISSUE THREAD

**Issue by yisibl** [kristoferjoseph/postcss-modular-scale#4]
The naming of CSS is semantic.

**Comment by kristoferjoseph** [comment]
?

**Comment by yisibl** [comment]
You should use a more semantic name, e.g. `modular-scale()`

**Comment by kristoferjoseph** [comment]
The `ms()` is inline with other shortened function names in the CSS spec. For instance `calc()` is not `calculation()`. I would rather type ms than modular-scale every time.
