### ISSUE TITLE
:root

### ISSUE THREAD

**Issue by eduarddotgg** [kristoferjoseph/postcss-modular-scale#5]
is there any way to not compile :root{}?

**Comment by kristoferjoseph** [comment]
Not sure what you are asking. What issue are you running into?

**Comment by lmartins** [comment]
I think he means that `:root` is outputted in the production CSS.

**Comment by kristoferjoseph** [comment]
Ok. That is per the CSS variables spec.

**Comment by kristoferjoseph** [comment]
This should be an issue in the postcss variables module.
