### ISSUE TITLE
Any way to have a unit by default?

### ISSUE THREAD

**Issue by lmartins** [kristoferjoseph/postcss-modular-scale#6]
Is there a way to avoid having to append the unit everytime I need a value;

That is:

``` sass
font-size: ms(4);
```

instead of this:

``` sass
font-size: ms(4)rem;
```

**Comment by kristoferjoseph** [comment]
I thought about this a lot. It would require adding code to output other units. The approach I took adds the least amount of code to this module while allowing the most flexibility.
