### ISSUE TITLE
console: undefined [undefined]

### ISSUE THREAD

**Issue by JamesJosephFinn** [kristoferjoseph/postcss-modular-scale#9]
The plugin works great, but this error gets printed to the console at compile time:

``` bash
src/css/styles.css
undefined [undefined]
```

The file listed above in the printout is actually just a manifest containing a bunch of `@import` statements. The source of the error is the `ms()` function. If I comment out the declaration in my typography partial, the error does not print.

Note that I am passing the `bases` and `ratios` arrays to the plugin in my config. I am not using the double hyphen vars in my stylesheet. This may be the cause.

Thanks for the great tool!

**Comment by VinSpee** [comment]
I'm also seeing this issue, but I am using double hyphen vars, so I don't think that's it. Any idea where it might be coming from?

**Comment by justinmetros** [comment]
Not sure of the solution, but I see part of the problem.

postcss-reporter doesn't like the result.messages.push() arguments. 

Commenting out lines 33,40 and 58 makes the undefined logs go away, and tool works just fine.

**Comment by justinmetros** [comment]
Hey Kris!

Awesome work on this, holmes!

Officially including this in new projects, replacing the sass version. Really love your implementation <3

Taking a slightly closer look, the results.message used in your tests seems to conflict with other post-css error-sniffing plugins.

Would you consider removing or refactoring them for the sake of keeping our consoles clean? 

Or be open to a pull request that addresses this?

Clearly the plugin works _extremely_ well, but it can be a bit confusing / distracting seeing those undefined errors when piping in some of the error reporting tools out there.

**Comment by kristoferjoseph** [comment]
@justinmetros Always open to making things better :)

**Comment by justinmetros** [comment]
Awesome :+1:

**Comment by VinSpee** [comment]
Thanks!
